version: '3'
services:
    graph-node-level:
        image: graphprotocol/graph-node
        ports:
            - '8000:8000'
            - '8001:8001'
            - '8020:8020'
            - '8030:8030'
            - '8040:8040'
        depends_on:
            - ipfs-level
            - postgres-level
        environment:
            node_id: 'index_node_bsc'
            PGHOST: postgres-level
            PGUSER: postgres
            PGPASSWORD: postgres
            ipfs: 'ipfs-level:5001'
            GRAPH_NODE_CONFIG: /config.toml
            BLOCK_INGESTOR: 'index_node_bsc'
        volumes:
            - ./config.toml:/config.toml

    postgres-level:
        image: postgres
        restart: always
        ports:
            - '5432:5432'
        command: postgres -c 'max_connections=1000'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_MULTIPLE_DATABASES: graph-node-bsc, graph-node-bsc-testnet
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
            - ./data/initdb:/docker-entrypoint-initdb.d

    ipfs-level:
        image: ipfs/go-ipfs:v0.10.0
        ports:
            - '5001:5001'
        volumes:
            - ./data/ipfs:/data/ipfs
