version: '3'
services:
    graph-nod:
        image: graphprotocol/graph-node
        ports:
            - '8000:8000'
            - '8001:8001'
            - '8020:8020'
            - '8030:8030'
            - '8040:8040'
        depends_on:
            - ipfs
            - postgres
        environment:
            node_id: 'index_node_linea'
            PGHOST: postgres
            PGUSER: postgres
            PGPASSWORD: postgres
            ipfs: 'ipfs:5001'
            GRAPH_NODE_CONFIG: /config.toml
            BLOCK_INGESTOR: 'index_node_linea'
        volumes:
            - ./config.toml:/config.toml

    postgres:
        image: postgres
        restart: always
        ports:
            - '5432:5432'
        command: postgres -c 'max_connections=1000'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_MULTIPLE_DATABASES: graph-node-linea, graph-node-linea-testnet
            POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
            - ./data/initdb:/docker-entrypoint-initdb.d

    ipfs:
        image: ipfs/kubo
        ports:
            - '5001:5001'
        volumes:
            - ./data/ipfs:/data/ipfs
